import { Tier } from "@prisma/client";

export const DEFAULT_COMPANIES: { name: string; city: string | null; tier: Tier }[] = [
  { name: "Coveo", city: "Montreal", tier: "MID" },
  { name: "Lightspeed", city: "Montreal", tier: "MID" },
  { name: "Nuvei", city: "Montreal", tier: "MID" },
  { name: "Genetec", city: "Montreal", tier: "MID" },
  { name: "Hopper", city: "Montreal", tier: "MID" },
  { name: "Workleap (GSoft)", city: "Montreal", tier: "MID" },
  { name: "Plusgrade", city: "Montreal", tier: "MID" },
  { name: "Dialogue", city: "Montreal", tier: "MID" },
  { name: "SSENSE", city: "Montreal", tier: "MID" },
  { name: "AlayaCare", city: "Montreal", tier: "MID" },
  { name: "Sonder", city: "Montreal", tier: "MID" },
  { name: "Poka", city: "Quebec City", tier: "MID" },
  { name: "Local Logic", city: "Montreal", tier: "MID" },
  { name: "Potloc", city: "Montreal", tier: "MID" },
  { name: "Super.com", city: "Toronto", tier: "MID" },
  { name: "Clutch", city: "Toronto", tier: "MID" },
  { name: "Jobber", city: "Edmonton", tier: "MID" },
  { name: "Wealthsimple", city: "Toronto", tier: "MID" },
  { name: "Clio", city: "Vancouver", tier: "MID" },
  { name: "Vidyard", city: "Kitchener", tier: "MID" },
  { name: "ApplyBoard", city: "Kitchener", tier: "MID" },
  { name: "Faire", city: "Toronto", tier: "MID" },
  { name: "Ada", city: "Toronto", tier: "MID" },
  { name: "Float", city: "Toronto", tier: "MID" },
  { name: "gaiia", city: "Vancouver", tier: "MID" },
  { name: "Doxel", city: "Vancouver", tier: "MID" },
  { name: "Uplifter Inc.", city: "Vancouver", tier: "MID" },
  { name: "Saltworks", city: "Vancouver", tier: "MID" },
  { name: "Puter Technologies", city: "Vancouver", tier: "MID" },
  { name: "ScalePad", city: "Vancouver", tier: "MID" },
  { name: "Weframe Tech", city: "Toronto", tier: "MID" },
  { name: "Digis", city: "Toronto", tier: "MID" },
  { name: "Modall", city: "Toronto", tier: "MID" },
  { name: "Themis Intelligence", city: "Toronto", tier: "MID" },
  { name: "SoumissionRenovation.ca", city: "Montreal", tier: "MID" },
  { name: "Petal Health", city: "Montreal", tier: "MID" },

  { name: "CGI", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Cofomo", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Alithya", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Levio", city: "Quebec City", tier: "CONSULTANCY" },
  { name: "Talsom", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Nexapp", city: "Quebec City", tier: "CONSULTANCY" },
  { name: "Spiria", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Osedea", city: "Montreal", tier: "CONSULTANCY" },
  { name: "Done Technologies", city: "Montreal", tier: "CONSULTANCY" },

  { name: "Shopify", city: "Ottawa", tier: "LARGE" },
  { name: "StackAdapt", city: "Toronto", tier: "LARGE" },
  { name: "Google", city: "Montreal", tier: "LARGE" },
  { name: "Microsoft", city: "Vancouver", tier: "LARGE" },
  { name: "Amazon", city: "Vancouver", tier: "LARGE" },
  { name: "Intact", city: "Montreal", tier: "LARGE" },
  { name: "Morgan Stanley", city: "Montreal", tier: "LARGE" },
  { name: "Autodesk", city: "Montreal", tier: "LARGE" },
  { name: "Square Enix", city: "Montreal", tier: "LARGE" },
  { name: "Ubisoft", city: "Montreal", tier: "LARGE" },
  { name: "Behaviour Interactive", city: "Montreal", tier: "LARGE" },
];
